_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.8
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": darwin-x86_64
epochs:
    value: 1000
learning_rate:
    value: 0.01
